export const styles = (theme) => ({
  productDetail: {
    width: "100%",
    boxShadow: "0 0 1.5px #aaa",
    margin: "70px auto",
    backgroundColor: "#fff",
    borderRadius: "5px",
  },
  bottomImageContainer: {
    width: "100%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
  },
  bottomImageParent: {
    width: "12%",
    margin: "0 6.5px",
    paddingTop: "28px",
    paddingBottom: "8px",
    cursor: "pointer",
    "&.active": {
      transform: "translate(0, 0.1px)",
      "&:after": {
        content: "''",
        position: "absolute",
        bottom: "0",
        width: "50%",
        left: "25%",
        borderBottom: "2.35px solid #ff5151",
      },
    },
  },
  bottomImage: {
    width: "100%",
  },
  storeName: {
    color: "#ff5151",
    fontSize: "16px",
    fontWeight: "500",
    cursor: "pointer",
    paddingTop: "4px",
  },
  productName: {
    color: "#333",
    fontSize: "22px",
    fontWeight: "450",
    marginBottom: "10px",
  },
  heading: {
    fontSize: "15px",
    fontWeight: "400",
    color: "#666",
    margin: "0",
    paddingLeft: "1px",
  },
  wishIcon: {
    color: "#777",
    marginRight: "7px",
    fontSize: "20px",
  },
  wishList: {
    padding: "10px 0",
    fontSize: "14px",
    color: "#777",
    textTransform: "none",
    fontWeight: "400",
    width: "220px",
    marginRight: "20px",
    "&:focus": {
      outline: "none",
    },
  },
  cartIcon: {
    color: "#fff",
    marginRight: "7px",
    fontSize: "22px",
  },
  cart: {
    padding: "10px 0",
    marginLeft: "20px",
    backgroundColor: "#FF5151",
    color: "#fff",
    width: "224px",
    fontWeight: "400",
    textTransform: "none",
    fontSize: "15px",
    boxShadow: "0 2px 4px 0 rgba(0, 0, 0, 0.2)",
    "&:hover": {
      backgroundColor: "#ed4040",
      color: "#fff",
      boxShadow: "0 2px 4px 0 rgba(0, 0, 0, 0.2)",
    },
    "&:focus": {
      outline: "none",
    },
  },
  price: {
    fontWeight: "500",
    fontSize: "17px",
    color: "#333",
    padding: "0 3px",
    textTransform: "none",
  },
  oPrice: {
    fontWeight: "400",
    fontSize: "14px",
    color: "#999",
    padding: "3px 3px 0 3px",
    textTransform: "none",
    textDecoration: "line-through",
  },
  discount: {
    fontWeight: "400",
    fontSize: "14px",
    color: "#ff5151",
    padding: "3px 3px 0 3px",
    textTransform: "none",
  },
  reviewContainer: {
    width: "100%",
    boxShadow: "0 0 1.5px #aaa",
    margin: "15px auto 70px auto",
    backgroundColor: "#fff",
    borderRadius: "5px",
  },
  reviewHeading: {
    padding: "32px 50px 25px 50px",
    fontSize: "18px",
    fontWeight: "500",
    color: "#333",
    margin: "0",
  },
  topBarContainer: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "column",
    margin: "50px 0",
  },
  ratingText: {
    color: "#555",
    fontWeight: "500",
    fontSize: "16px",
    margin: "0",
    paddingTop: "7px",
    letterSpacing: "1px",
  },
  nStars: {
    color: "#999",
    fontSize: "12px",
    paddingRight: "1%",
    whiteSpace: "nowrap",
    marginRight: "15px",
    fontWeight: "400",
  },
  nStarOuter: {
    width: "220px",
    height: "15px",
    borderRadius: "3px",
    backgroundColor: " #F4F4F4",
    marginTop: "1%",
  },
  nStarInner: {
    borderRadius: "3px",
    height: "100%",
    backgroundColor: "#FBC623",
  },
});
